  
name: CI

on:
  create:
    branches:
      - release/**
  push:
    branches:
    - master
    paths:
    - ToastNotification/**
    - ToastNotification.Wasm/**
    - ToastNotification.Wpf/**
    - ToastNotificationDemo/**
    - .github/workflows/ci.yml
  pull_request:
    branches:
    - master
    paths:
    - ToastNotification/**
    - ToastNotification.Wasm/**
    - ToastNotification.Wpf/**
    - ToastNotificationDemo/**
    - .github/workflows/ci.yml

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'ToastNotification.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild $env:SOLUTION /p:Configuration=$env:BUILD_CONFIG /p:Platform="Any CPU" -p:Version=$env:BUILD_VERSION

    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --no-restore --no-build --verbosity normal

    - name: Build nuget packages
      run: |
        nuget pack ToastNotification.Uno.nuspec -Version 0.0.0-preview-${{ github.run_number }}-${{ github.run_id }}
        nuget pack ToastNotification.Uno.Wpf.nuspec -Version 0.0.0-preview-${{ github.run_number }}-${{ github.run_id }}
        nuget pack ToastNotification.Uno.Wasm.nuspec -Version 0.0.0-preview-${{ github.run_number }}-${{ github.run_id }}

    - name: Publish ToastNotification.Uno
      uses: actions/upload-artifact@v2
      with:
        name: ToastNotification.Uno.0.0.0-preview-${{ github.run_number }}-${{ github.run_id }}.nupkg
        path: ToastNotification.Uno.0.0.0-preview-${{ github.run_number }}-${{ github.run_id }}.nupkg

    - name: PublishToastNotification.Uno.Wpf
      uses: actions/upload-artifact@v2
      with:
        name: ToastNotification.Uno.Wpf.0.0.0-preview-${{ github.run_number }}-${{ github.run_id }}.nupkg
        path: ToastNotification.Uno.Wpf.0.0.0-preview-${{ github.run_number }}-${{ github.run_id }}.nupkg

    - name: Publish ToastNotification.Uno.Wasm
      uses: actions/upload-artifact@v2
      with:
        name: ToastNotification.Uno.Wasm.0.0.0-preview-${{ github.run_number }}-${{ github.run_id }}.nupkg
        path: ToastNotification.Uno.Wasm.0.0.0-preview-${{ github.run_number }}-${{ github.run_id }}.nupkg

    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
