  
name: CI

on:
  create:
    branches:
      - release/**
  push:
    branches:
    - master
    paths:
    - ToastNotification/**
    - ToastNotification.Wasm/**
    - ToastNotification.Wpf/**
    - ToastNotificationDemo/**
    - .github/workflows/ci.yml
  pull_request:
    branches:
    - master
    paths:
    - ToastNotification/**
    - ToastNotification.Wasm/**
    - ToastNotification.Wpf/**
    - ToastNotificationDemo/**
    - .github/workflows/ci.yml

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'ToastNotification.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF -BuildNumber ${{ github.run_number }} -BuildId ${{ github.run_id }}
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild $env:SOLUTION /p:Configuration=$env:BUILD_CONFIG /p:Platform="Any CPU" -p:Version=$env:BUILD_VERSION

    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --no-restore --no-build --verbosity normal

    - name: Build nuget packages
      run: |
        cd build
        Import-Module .\TransformNuspec.psm1
        TransformNuspec -BuildVersion $env:BUILD_VERSION

    - name: Publish ToastNotification.Uno artifact
      uses: actions/upload-artifact@v2
      with:
        name: ToastNotification.Uno.${{ env.BUILD_VERSION }}.nupkg
        path: build/ToastNotification.Uno.${{ env.BUILD_VERSION }}.nupkg

    - name: Publish ToastNotification.Uno.Wpf artifact
      uses: actions/upload-artifact@v2
      with:
        name: ToastNotification.Uno.Wpf.${{ env.BUILD_VERSION }}.nupkg
        path: build/ToastNotification.Uno.Wpf.${{ env.BUILD_VERSION }}.nupkg

    - name: Publish ToastNotification.Uno.Wasm artifact
      uses: actions/upload-artifact@v2
      with:
        name: ToastNotification.Uno.Wasm.${{ env.BUILD_VERSION }}.nupkg
        path: build/ToastNotification.Uno.Wasm.${{ env.BUILD_VERSION }}.nupkg

    - name: Publish ToastNotification.Uno.Gtk artifact
      uses: actions/upload-artifact@v2
      with:
        name: ToastNotification.Uno.Gtk.${{ env.BUILD_VERSION }}.nupkg
        path: build/ToastNotification.Uno.Gtk.${{ env.BUILD_VERSION }}.nupkg

    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
